# >>> LLM-COMPOSE: START
version: '3.8'
services:
  aichatbotpro:
    build: .
    container_name: aichatbotpro_app
    ports:
    - "8002:8002"
    environment:
      - FLASK_ENV=production
    command: /app/.venv/bin/python app.py
# >>> LLM-COMPOSE: END
